Repository USGS-WiM/StreamStats, pull requests merged in 2023-02, with the labels that each got.

#1521 Gageplots into SC-Runoff
  CHANGELOG.md
  dist/Views/gagepage.html
  dist/scripts/vendor.min.js
  package-lock.json
  package.json
  src/Controllers/GagePageController.js
  src/Controllers/GagePageController.ts
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
  src/Services/ModalService.ts
  src/Views/gagepage.html
  src/config.js
  src/config.ts
  src/index.html
Labels: South Carolina

#1522 Fix gageplots build errors
  dist/scripts/custom.min.js
  dist/scripts/vendor.min.js
  src/index.html
Labels: gage plots

#1523 Gageplots into SC-Runoff
  dist/scripts/custom.min.js
  dist/scripts/vendor.min.js
  src/index.html
Labels: South Carolina

#1525 Fixes #1524 - Change lc06imp to lc19imp in Bohman Urban
  dist/scripts/custom.min.js
  src/Controllers/SCStormRunoffController.js
  src/Controllers/SCStormRunoffController.ts
Labels: South Carolina

#1530 Fixes #1529 - NHD Streams Intersecting Basin Delineation Boundary is broken
  dist/scripts/custom.min.js
  src/Services/StudyAreaService.js
  src/Services/StudyAreaService.ts
Labels: South Carolina

#1531 Fixes #1456 - Created BP modal
  src/Controllers/BatchProcessorController.js
  src/Controllers/BatchProcessorController.ts
  src/Controllers/NavbarController.js
  src/Controllers/NavbarController.ts
  src/Services/ModalService.js
  src/Services/ModalService.ts
  src/Views/batchprocessor.html
  src/Views/navigationview.html
  src/index.html
Labels: Batch Processor

#1533 Fixes #1532 query NHD on map
  dist/scripts/custom.min.js
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
Labels: South Carolina

#1541 Fixes #1457: Add Select State/Region Dropdown
  src/Controllers/BatchProcessorController.js
  src/Controllers/BatchProcessorController.ts
  src/Services/nssService.js
  src/Services/nssService.ts
  src/Views/batchprocessor.html
  src/appConfig.js
Labels: Batch Processor

#1548 Fixes #1547
  dist/scripts/custom.min.js
  src/Controllers/SCStormRunoffController.js
  src/Controllers/SCStormRunoffController.ts
Labels: South Carolina

#1549 Fixes #1546
  src/Controllers/SCStormRunoffController.js
  src/Controllers/SCStormRunoffController.ts
  src/Views/scstormrunoff.html
Labels: South Carolina

#1552 Fixes #1551 - Error in SC Flood Hydrograph for Urban Watersheds
  dist/scripts/custom.min.js
  src/Controllers/SCStormRunoffController.js
  src/Controllers/SCStormRunoffController.ts
Labels: South Carolina

#1554 Fixes #1458: Add flow statistics checklist
  src/Controllers/BatchProcessorController.js
  src/Controllers/BatchProcessorController.ts
  src/Services/nssService.js
  src/Services/nssService.ts
  src/Views/batchprocessor.html
  src/appConfig.js
Labels: Batch Processor
