Repository USGS-WiM/StreamStats, pull requests merged in 2024-01, with the labels that each got.

#1890 Part of #1861 - prepare BP for official use
  CHANGELOG.md
  dist/Views/batchprocessor.html
  dist/appConfig.js
  dist/appConfig_dev.js
  dist/appConfig_test.js
  src/Views/batchprocessor.html
  src/appConfig.js
  src/appConfig_dev.js
  src/appConfig_test.js
Labels: Batch Processor

#1895 fixed broken links in sidebar
  CHANGELOG.md
  src/Views/sidebarview.html
Labels: bug

#1881 Fixes #1846 "NHD Features of Delineated Basin" feature not working, Fixes #1571 - added error message to report
  dist/Views/reportview.html
  dist/scripts/custom.min.js
  src/Controllers/ReportController.js
  src/Controllers/ReportController.ts
  src/Services/StudyAreaService.js
  src/Services/StudyAreaService.ts
  src/Views/reportview.html
Labels: South Carolina

#1884 Fixes #1883 - Bugs with delineate buttons
  dist/Views/sidebarview.html
  dist/scripts/custom.min.js
  dist/scripts/vendor.min.js
  package-lock.json
  package.json
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
  src/Controllers/SidebarController.js
  src/Controllers/SidebarController.ts
  src/Services/StudyAreaService.js
  src/Services/StudyAreaService.ts
  src/Views/sidebarview.html
Labels: South Carolina

#1885 Part of #1852
  dist/scripts/custom.min.js
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
Labels: South Carolina

#1898 Fixes #1876 BP: Download Stream Grids tab has double entries
  CHANGELOG.md
  dist/Views/batchprocessor.html
  src/Views/batchprocessor.html
Labels: bug, Batch Processor

#1902 Part of #1852
  dist/scripts/custom.min.js
  dist/scripts/vendor.min.js
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
  src/Controllers/SidebarController.js
  src/Controllers/SidebarController.ts
  src/Services/StudyAreaService.js
  src/Services/StudyAreaService.ts
Labels: South Carolina

#1901 #1904, Part of #1852 - longest flow path, disable extra functions, fix storm runoff models
  dist/Views/explorationview.html
  dist/Views/mapview.html
  dist/Views/nearestgages.html
  dist/Views/reportview.html
  dist/Views/scstormrunoff.html
  dist/Views/sidebarview.html
  dist/scripts/custom.min.js
  src/Controllers/ExtensionModalController.js
  src/Controllers/ExtensionModalController.ts
  src/Controllers/FlowAnywhereController.js
  src/Controllers/FlowAnywhereController.ts
  src/Controllers/MapController.js
  src/Controllers/MapController.ts
  src/Controllers/NearestGagesController.js
  src/Controllers/NearestGagesController.ts
  src/Controllers/ReportController.js
  src/Controllers/ReportController.ts
  src/Controllers/SCStormRunoffController.js
  src/Controllers/SCStormRunoffController.ts
  src/Controllers/StormRunoffController.js
  src/Controllers/StormRunoffController.ts
  src/Controllers/WateruseController.js
  src/Controllers/WateruseController.ts
  src/Services/StudyAreaService.js
  src/Services/StudyAreaService.ts
  src/Views/explorationview.html
  src/Views/mapview.html
  src/Views/nearestgages.html
  src/Views/reportview.html
  src/Views/scstormrunoff.html
  src/Views/sidebarview.html
Labels: South Carolina
